development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:aeefcb0ef40e0d16f962746e5a0cd60a@pike.redistogo.com:10056/
  channel_prefix: channelchat_production
